// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XqjgvhKzZ4n3l4NB8NsMqB1pZYKcFmg',
    appId: '1:412496371299:web:f6be46c735aeab7f6e2256',
    messagingSenderId: '412496371299',
    projectId: 'store-app-3afdc',
    authDomain: 'store-app-3afdc.firebaseapp.com',
    storageBucket: 'store-app-3afdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD_xkMj5DlNl0RxNMK6Am1StQ5Tu0CgCg',
    appId: '1:412496371299:android:711170fa2949c7776e2256',
    messagingSenderId: '412496371299',
    projectId: 'store-app-3afdc',
    storageBucket: 'store-app-3afdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAef9eLBmr-ySVIMZp3DjeD-vOonT6fkk0',
    appId: '1:412496371299:ios:81f5640db6fed9b06e2256',
    messagingSenderId: '412496371299',
    projectId: 'store-app-3afdc',
    storageBucket: 'store-app-3afdc.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );
}
